apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Experiments Homepage
  description: |
    Homepage of Mhess Experiments
  links:
    - title: Website
      url: http://backstage.io
  annotations:
    github.com/project-slug: mhess-experiments/mhess-experiments.github.io
    #backstage.io/techdocs-ref: url:https://github.com/backstage/backstage
    #lighthouse.com/website-url: https://backstage.io
spec:
  type: website
  lifecycle: experimental
  owner: mhess126@gmail.com

